// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf_qVB72-lO5VhmvJciXGjiJB5DDecGfw',
    appId: '1:557889947661:web:257b9f999bbf252787ad44',
    messagingSenderId: '557889947661',
    projectId: 'medrayder-flutter',
    authDomain: 'medrayder-flutter.firebaseapp.com',
    storageBucket: 'medrayder-flutter.firebasestorage.app',
    measurementId: 'G-BJJLS97CTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCFV7PxMrk7X__mxTb5jA3pVBGo3txf8',
    appId: '1:557889947661:android:9302d533e0f70a3e87ad44',
    messagingSenderId: '557889947661',
    projectId: 'medrayder-flutter',
    storageBucket: 'medrayder-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOyoFW5VwMuBJrImvEBJ_S3DU69kpWURo',
    appId: '1:557889947661:ios:b4db6d7b2a26075887ad44',
    messagingSenderId: '557889947661',
    projectId: 'medrayder-flutter',
    storageBucket: 'medrayder-flutter.firebasestorage.app',
    iosBundleId: 'com.medrayder.meddoctors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOyoFW5VwMuBJrImvEBJ_S3DU69kpWURo',
    appId: '1:557889947661:ios:7c366b570e9289b587ad44',
    messagingSenderId: '557889947661',
    projectId: 'medrayder-flutter',
    storageBucket: 'medrayder-flutter.firebasestorage.app',
    iosBundleId: 'com.medrayder.doctors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf_qVB72-lO5VhmvJciXGjiJB5DDecGfw',
    appId: '1:557889947661:web:89758d812c3dc2a387ad44',
    messagingSenderId: '557889947661',
    projectId: 'medrayder-flutter',
    authDomain: 'medrayder-flutter.firebaseapp.com',
    storageBucket: 'medrayder-flutter.firebasestorage.app',
    measurementId: 'G-SC8NYN5YPS',
  );
}